version: "3.8"
services:
  whosatmyfeeder:
    build: https://github.com/ando01/WhosAtMyFeeder.git
    container_name: whosatmyfeeder
    restart: unless-stopped
    image: whosatmyfeeder
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - 7766:7766 #port used by the webserver in the container is defined in config.
    environment:
      - TZ=America/New_York
